---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cass-server
spec:
  selector:
    matchLabels:
      app: cass-server
  replicas: 1
  template:
    metadata:
      labels:
        app: cass-server
    spec:
      containers:
      - name: cassandra
        image: docker.io/cassandra
        ports:
        - containerPort: 9042
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-svc
  labels:
    app: cass-server
spec:
  ports:
  - port: 9042
    name: cassandra-port
    targetPort: 9042
    protocol: TCP
  selector:
    app: cass-server
---
---
apiVersion: v1
kind: Service
metadata:
  name: cass-web-external
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: cassandra-web
  type: LoadBalancer

---
apiVersion: v1
kind: Pod
metadata:
  name: cassandra-web
  labels:
    app: cassandra-web
spec:
  containers:
  - env:
    - name: CASSANDRA_HOST_IPS
      value: "cassandra-svc"
    - name: CASSANDRA_PORT
      value: '9042'
    - name: CASSANDRA_USER
      value: cassandra
    - name: CASSANDRA_PASSWORD
      value: cassandra
    name: cassandra-web
    image: markusgulden/cassandra-web
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3000
      protocol: TCP
  terminationGracePeriodSeconds: 0
